architectury {
    common(rootProject.enabled_platforms.split(","))
}

repositories {
    maven {
        name = 'Sleeping Town'
        url = 'https://repo.sleeping.town/'
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    implementation include("folk.sisby:kaleido-config:${rootProject.kaleido_version}")
}
