# Gradle Properties
org.gradle.jvmargs=-Xmx2G

# Architectury Properties
minecraft_version=1.21.1
minecraft_version_base=1.21
parchment_mappings=2024.11.17
enabled_platforms=fabric,neoforge
fabric_loader_version=0.16.14
fabric_api_version=0.116.6+1.21.1
neoforge_version=21.1.208

# Mod Properties
mod_version=3.0.0
maven_group=cc.unilock
archives_base_name=sorted_enchantments

# Dependencies
kaleido_version=0.3.3+1.3.2
