modLoader = "lowcodefml"
loaderVersion = "[41,)"
license = "MIT"

issueTrackerURL="https://github.com/unilock/SortedEnchantments/issues"

[[mods]]
modId = "sorted_enchantments"
version = "${version}"
displayName = "Sorted Enchantments"
displayURL="https://github.com/unilock/SortedEnchantments"
authors="unilock"
description = '''
Sorts enchantments in tooltips (alphabetically)
'''

[[dependencies.sorted_enchantments]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sorted_enchantments]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "CLIENT"
